# Configuración general de la aplicación
spring.application.name=WarMetrics
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Excluimos los endpoints de info y health para que no sean accesibles públicamente
management.endpoints.web.exposure.exclude=info,health

# Información de la aplicación que se mostrará en el endpoint /actuator/info
info.app.name=War-Metrics
info.app.description=Aplicación para realizar simulacros de tiradas en warhammer 40000
info.app.version=1.0.0

# --- CONFIGURACIÓN DE LA BASE DE DATOS H2 ---
# Le damos un nombre a nuestra base de datos (warmetricsdb)
spring.datasource.url=jdbc:h2:file:./data/warmetricsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Habilitamos la consola web de H2 para poder ver las tablas visualmente
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- CONFIGURACIÓN DE JPA / HIBERNATE ---
# Le decimos a Spring que cree o actualice las tablas automáticamente según nuestras clases de Java
spring.jpa.hibernate.ddl-auto=update
# Nos mostrará en la consola el código SQL que genera por debajo para que podamos entender mejor lo que está haciendo
spring.jpa.show-sql=true