spring.application.name=Proyecto1
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

management.endpoints.web.exposure.exclude=info,health

spring.security.user.name=user
spring.security.user.password=1234

info.app.name=War-Metrics
info.app.description=Aplicación para realizar simulacros de tiradas en warhammer 40000
info.app.version=1.0.0